#  last version: 2024-10-10
---
- name: install docker engine
  hosts: xxx

  tasks:
      - name: remove old pakages
        shell: |
            apt-get remove docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc
        ignore_errors: true

      - name: update & upgrade
        apt:
            update_cache: true
            upgrade: full

      - name: "install package {{ item }}"
        apt:
            name: "{{ item }}"
            state: present
        loop:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release

      - name: Add Docker official GPG key
        shell: |
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc

      - name: Add the repository to Apt sources
        shell: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: update & upgrade
        apt:
            update_cache: true
            upgrade: safe

      - name: Install docker {{ item }} 
        apt:
            name: "{{ item }}"
            state: present
        loop:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
            - docker-buildx-plugin

      - name: enable services
        shell: |
            systemctl enable docker.service
            systemctl enable containerd.service

      - name: version
        shell: docker -v
        register: status
      - debug:
            msg: "{{ status.stdout_lines }}"
