# last version 2024-10-10
- name: install neovim
  hosts: xxx

  tasks:
      - name: aggiorna apt
        apt:
            update_cache: true

      - name: install dependencies
        apt:
            pkg:
                - software-properties-common
                - build-essential
                - python3-dev
                - python3-pip
                - git
                - curl

      - name: install neovim
        shell: |
            curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
            rm -rf /opt/nvim
            tar -C /opt -xzf nvim-linux64.tar.gz
            echo 'export PATH=$PATH:/opt/nvim-linux64/bin' >> ~/.bashrc 
            source ~/.bashrc 
            rm nvim-linux64.tar.gz 

      - name: install LazyVim
        shell: |
            mv ~/.config/nvim{,.bak}
            mv ~/.local/share/nvim{,.bak}
            mv ~/.local/state/nvim{,.bak}
            mv ~/.cache/nvim{,.bak}
            git clone https://github.com/LazyVim/starter ~/.config/nvim
            rm -rf ~/.config/nvim/.git
